name: Keep Render Alive
on:
  schedule:
    - cron: "*/5 * * * *"  # Chạy mỗi 5 phút
jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        run: curl -X GET https://scoreapi-1zqy.onrender.com/Auths/GetAllAdmins
